version: '3.7'

services:
  postgres:
    image: postgis/postgis:12-3.0-alpine
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=sg_scraper_dev'
    ports:
      - '5432:5432'

