version: '3.7'

services:
  scrape:
    build: .
    stdin_open: true
    tty: true
    environment:
      - 'DATABASE_URL=postgres:postgres@postgres/sg_scraper_dev'
  postgres:
    image: postgres:13-alpine
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=sg_scraper_dev'

